export { faTachometerAlt,
  faUserGraduate,
  faChalkboardTeacher,
  faBolt,
  faTasks,
  faInbox,
  faUsersCog,
  faBook,
  faCalendarAlt,
  faFileAlt,
  faBullhorn } from "@fortawesome/free-solid-svg-icons";
