export {
  faTachometerAlt,
  faUserGraduate,
  faChalkboardTeacher,
  faBolt,
  faTasks,
  faInbox,
  faUsersCog,
  faBook,
  faCalendarAlt,
  faFileAlt,
  faBullhorn,
  faUserShield,
  faUserCheck,
  faUsers,
  faPlusCircle,
  faSearch,
  faDownload,
  faEnvelope,
  faEye,
  faPen,
  faChevronLeft,
  faChevronRight
} from "@fortawesome/free-solid-svg-icons";
